# scan-music.ps1 - scan LOU\music and generate LOU\music-list.js (offline fallback playlist)
# Usage:  powershell -ExecutionPolicy Bypass -File scan-music.ps1
# Notes:  this file must stay ASCII-only. It is run by Windows PowerShell 5.1,
#         which mis-decodes UTF-8 .ps1 files that have no BOM, so never let an
#         editor rewrite it without a BOM.
[CmdletBinding()]
param(
  [string]$MusicDir,
  [string]$Out,
  [switch]$AlsoJson,
  [switch]$NoOpen
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
if (-not $MusicDir) { $MusicDir = Join-Path $Root "LOU\music" }
if (-not $Out)      { $Out      = Join-Path $Root "LOU\music-list.js" }
$audioExt = @(".mp3", ".flac", ".m4a", ".aac", ".wav", ".ogg", ".oga", ".opus", ".wma", ".ape")

# ---------- name parsing: "10.1 singer - title" style file names ----------
function Split-TrackName {
  param([string]$Base)

  $name = $Base
  $no = $null
  $rest = $name

  # leading number: 10.1 / 6.0 / 11song / 3.gem / 3 pearl
  $m = [regex]::Match($name, '^(\d+(?:\.\d+)?)\s*[\.、]?\s*(?=\S)(.*)$')
  if ($m.Success) {
    $candidate = [double]$m.Groups[1].Value
    $tail = $m.Groups[2].Value
    # do not treat "4K" style tokens as track numbers
    if ($tail -notmatch '^\d') {
      $no = $candidate
      $rest = $tail
    }
  }

  $artist = ""
  $title = $rest
  $parts = [regex]::Split($rest, '\s+[-–—]\s*')
  if ($parts.Count -ge 2) {
    $title = $parts[0].Trim()
    $artist = ($parts[1..($parts.Count - 1)] -join " - ").Trim()
  }

  $title = $title.Trim()
  if ($title -eq "") { $title = $Base }
  $artist = $artist -replace '_', ' / ' -replace '\|', ' / '
  $artist = ($artist -split '/' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }) -join " / "

  [pscustomobject]@{ no = $no; title = $title; artist = $artist }
}

if (-not (Test-Path -LiteralPath $MusicDir)) {
  Write-Host ("  [x] music folder not found: " + $MusicDir) -ForegroundColor Red
  exit 1
}

Write-Host ""
Write-Host "  Luotianyi fanpage - offline playlist generator" -ForegroundColor Cyan
Write-Host ("  music: " + $MusicDir)

# ---------- scan ----------
$list = New-Object System.Collections.Generic.List[object]
Get-ChildItem -LiteralPath $MusicDir -Recurse -File | ForEach-Object {
  $ext = $_.Extension.ToLower()
  if ($audioExt -notcontains $ext) { return }

  $rel   = $_.FullName.Substring($MusicDir.Length).TrimStart("\", "/")
  $relU  = $rel -replace '\\', '/'
  $relE  = (($relU -split '/') | ForEach-Object { [uri]::EscapeDataString($_) }) -join '/'
  $segs  = $relU -split '/'
  $folder = ""
  if ($segs.Count -gt 1) { $folder = ($segs[0..($segs.Count - 2)] -join "/") }

  $p = Split-TrackName -Base $_.BaseName
  $list.Add([ordered]@{
    id     = $relU
    file   = $relE
    name   = $_.Name
    folder = $folder
    no     = $p.no
    title  = $p.title
    artist = $p.artist
    ext    = $ext.TrimStart(".").ToUpper()
    size   = $_.Length
  })
}

# ---------- sort: by number, then name ----------
$sorted = @($list | Sort-Object `
    @{ Expression = { if ($null -eq $_.no) { [double]::MaxValue } else { [double]$_.no } } }, `
    @{ Expression = { $_.name } })

$baseUtc = [DateTime]::new(1970, 1, 1, 0, 0, 0, [DateTimeKind]::Utc)
$maxMs = [long]0
foreach ($t in $sorted) {
  $f = [System.IO.FileInfo]::new((Join-Path $MusicDir ($t.id -replace '/', '\')))
  if (-not $f.Exists) { continue }
  $ms = [long]([DateTime]::SpecifyKind($f.LastWriteTimeUtc, [DateTimeKind]::Utc) - $baseUtc).TotalMilliseconds
  if ($ms -gt $maxMs) { $maxMs = $ms }
}
# keep the same shape as /api/tracks: "<newest mtime ms>-<track count>"
$version = ([string]$maxMs) + "-" + ([string]$sorted.Count)

$payload = [ordered]@{
  version     = $version
  generatedAt = [long][DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
  root        = "LOU/music"
  total       = $sorted.Count
  tracks      = $sorted
}

$json = $payload | ConvertTo-Json -Depth 8 -Compress
# keep JSON safe to embed inside a script tag
$jsonSafe = $json -replace '<', '\u003c' -replace '>', '\u003e'

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by scan-music.ps1 - do not edit by hand */")
[void]$sb.AppendLine("/* " + (Get-Date).ToString("yyyy-MM-dd HH:mm:ss") + " | tracks: " + $sorted.Count + " */")
[void]$sb.AppendLine("window.LUOTIANYI_MUSIC = " + $jsonSafe + ";")
[void]$sb.AppendLine("window.LUOTIANYI_MUSIC.generatedBy = ""scan-music.ps1"";")

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($Out, $sb.ToString(), $utf8NoBom)
Write-Host ("  [ok] wrote " + $Out) -ForegroundColor Green

if ($AlsoJson) {
  $jsonOut = [System.IO.Path]::ChangeExtension($Out, ".json")
  [System.IO.File]::WriteAllText($jsonOut, $json, $utf8NoBom)
  Write-Host ("  [ok] wrote " + $jsonOut) -ForegroundColor Green
}

$maxNo = 0
foreach ($t in $sorted) { if ($null -ne $t.no -and $t.no -gt $maxNo) { $maxNo = $t.no } }

Write-Host ""
Write-Host ("  tracks: " + $sorted.Count + "   max number: " + $maxNo) -ForegroundColor Yellow
Write-Host ""
Write-Host "  no    title                          artist" -ForegroundColor DarkGray
$i = 0
foreach ($t in $sorted) {
  $i++
  $noS = "--"
  if ($null -ne $t.no) { $noS = ([string]$t.no) }
  $line = ("  {0,2}. {1,-5} {2,-30} {3}" -f $i, $noS, $t.title, $t.artist)
  Write-Host $line
}

Write-Host ""
Write-Host "  Tip: drag the whole luotianyi-fanpage folder anywhere - relative paths keep working." -ForegroundColor DarkGray
Write-Host "  Tip: double click start-player.cmd for live scanning (new songs show up on refresh)." -ForegroundColor DarkGray
Write-Host ""

$index = Join-Path $Root "LOU\index.html"
if ((-not $NoOpen) -and (Test-Path -LiteralPath $index)) {
  Start-Process $index
}
